// Mock API service for frontend-only deployment
export const mockApi = {
  // Mock chat API endpoints
  chat: {
    async sendQuery(userId: string, sessionId: string, query: string) {
      // Simulate API delay
      await new Promise(resolve => setTimeout(resolve, 500));
      
      return {
        success: true,
        response: `This is a mock response to your query: "${query}". In a real deployment, this would come from the backend API.`,
        sources: [],
        timestamp: new Date().toISOString()
      };
    },

    async uploadFile(userId: string, sessionId: string, file: File) {
      await new Promise(resolve => setTimeout(resolve, 1000));
      
      return {
        success: true,
        fileId: `mock_file_${Date.now()}`,
        fileName: file.name,
        message: 'File uploaded successfully (mock)'
      };
    },

    async getAllSessions(userId: string) {
      return [
        {
          sessionId: 'mock_session_1',
          chatName: 'Sample Conversation',
          messageCount: 3,
          lastMessage: 'How can I help you today?',
          createdAt: new Date(Date.now() - 86400000), // 1 day ago
          updatedAt: new Date()
        }
      ];
    },

    async getSessionDetails(userId: string, sessionId: string) {
      return {
        userId,
        sessionId,
        chromaCollectionName: 'mock_collection',
        messages: [
          {
            id: '1',
            content: 'Hello! How can I assist you today?',
            role: 'assistant',
            timestamp: new Date(Date.now() - 300000).toISOString(), // 5 minutes ago
          },
          {
            id: '2',
            content: 'Can you help me understand how this works?',
            role: 'user',
            timestamp: new Date(Date.now() - 120000).toISOString(), // 2 minutes ago
          },
          {
            id: '3',
            content: 'Sure! This is a demonstration of the frontend functionality. In a real deployment, this would connect to our backend services.',
            role: 'assistant',
            timestamp: new Date().toISOString(),
          }
        ],
        createdAt: new Date(Date.now() - 86400000),
        updatedAt: new Date(),
        language: 'en',
        grade: '10'
      };
    }
  },

  // Mock board API endpoints
  board: {
    async checkOllamaStatus() {
      return { connected: true, model: 'mock-model' };
    },

    async generateCards(prompt: string, cardCount: number = 3) {
      await new Promise(resolve => setTimeout(resolve, 1000));
      
      const mockCards = Array.from({ length: cardCount }, (_, i) => ({
        id: `mock-card-${i + 1}`,
        title: `Concept ${i + 1}`,
        content: `This is a mock card demonstrating concept ${i + 1}. In a real deployment, this would be generated by the backend AI service based on your prompt: "${prompt}"`,
      }));

      return mockCards;
    },

    async performCardAction(action: string, cardContents: string[]) {
      await new Promise(resolve => setTimeout(resolve, 800));
      
      return {
        success: true,
        action,
        result: `Mock result for action "${action}" on ${cardContents.length} cards. This would be processed by the backend in a real deployment.`,
      };
    }
  },

  // Mock browse/file endpoints
  browse: {
    async getSessionDocuments(userId: string, sessionId: string) {
      return [
        {
          fileId: 'mock-doc-1',
          fileName: 'sample-document.pdf',
          language: 'en',
          pageCount: 10,
          uploadedAt: new Date()
        }
      ];
    }
  }
};