// Simple API mock for deployed environments
// Only activates when not on localhost

const isDeployed = typeof window !== 'undefined' && 
                  window.location.hostname !== 'localhost' && 
                  !window.location.hostname.startsWith('127.') &&
                  !window.location.hostname.startsWith('192.');

if (isDeployed) {
  console.log('API Mock: Activated for deployed environment');
  
  // Store original fetch
  const originalFetch = window.fetch;
  
  // Override fetch to intercept API calls
  window.fetch = async function(url, options) {
    // If this is an API call, return mock response
    if (typeof url === 'string' && url.includes('/api/')) {
      console.log(`API Mock: Intercepted call to ${url}`);
      
      // Generate mock responses based on the endpoint
      if (url.includes('/api/query') || url.includes('/api/chats')) {
        return new Response(JSON.stringify({
          success: true,
          response: "This is a demonstration response. In a full deployment, this would connect to our AI backend.",
          sources: [],
          message: "Demo mode: Backend API not connected"
        }), {
          status: 200,
          headers: { 'Content-Type': 'application/json' }
        });
      } else if (url.includes('/api/upload')) {
        return new Response(JSON.stringify({
          success: true,
          fileId: 'demo-file-' + Date.now(),
          fileName: 'demo-file.pdf',
          message: 'File upload simulated in demo mode'
        }), {
          status: 200,
          headers: { 'Content-Type': 'application/json' }
        });
      } else if (url.includes('/api/board')) {
        if (url.includes('/ollama/status')) {
          return new Response(JSON.stringify({
            connected: true,
            model: 'demo-model',
            message: 'Demo mode: Board API simulated'
          }), {
            status: 200,
            headers: { 'Content-Type': 'application/json' }
          });
        } else {
          return new Response(JSON.stringify({
            success: true,
            cards: [
              { id: 'demo-1', title: 'Demo Card 1', content: 'This is a demonstration card. In a full deployment, this would be generated by our AI backend.' },
              { id: 'demo-2', title: 'Demo Card 2', content: 'This is another demonstration card showing how the system would work with real backend integration.' }
            ],
            message: 'Demo mode: Board API simulated'
          }), {
            status: 200,
            headers: { 'Content-Type': 'application/json' }
          });
        }
      } else if (url.includes('/api/browse') || url.includes('/api/files')) {
        return new Response(JSON.stringify({
          files: [
            { fileId: 'demo-file-1', fileName: 'sample-document.pdf', count: 10 }
          ],
          sessions: [],
          message: 'Demo mode: File API simulated'
        }), {
          status: 200,
          headers: { 'Content-Type': 'application/json' }
        });
      } else {
        // Generic mock response for other API endpoints
        return new Response(JSON.stringify({
          success: true,
          message: 'Demo mode: This would connect to the backend API in a full deployment',
          data: {}
        }), {
          status: 200,
          headers: { 'Content-Type': 'application/json' }
        });
      }
    }
    
    // For non-API calls (like static assets), use original fetch
    return originalFetch.call(this, url, options);
  };
}

export {};